(function(){
var peers=[],canManage=false,secureMode=false,localInfo=null,speedSamples=[];
function q(id){return document.getElementById(id)}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function fmtBytes(n){var u=['B','KB','MB','GB','TB'],i=0;if(typeof n!=='number'||isNaN(n))return '-';while(n>=1024&&i<u.length-1){n/=1024;i++}return n.toFixed(i===0?0:1)+' '+u[i]}
function ajax(method,url,body,done,fail,contentType){var x=new XMLHttpRequest();x.open(method,url,true);x.timeout=0;if(contentType)x.setRequestHeader('Content-Type',contentType);x.onreadystatechange=function(){if(x.readyState===4){if(x.status>=200&&x.status<300){done&&done(x)}else{fail&&fail(x)}}};x.onerror=function(){fail&&fail(x)};x.send(body==null?null:body);return x}
function json(method,url,obj,done,fail){return ajax(method,url,obj==null?null:JSON.stringify(obj),done,fail,'application/json; charset=utf-8')}
function fnv(s,seed){var h=seed||2166136261,i;for(i=0;i<s.length;i++){h^=s.charCodeAt(i);h=(h*16777619)>>>0}return ('00000000'+h.toString(16)).slice(-8)}
function uploadID(file,target){var s=((localInfo&&localInfo.id)||'local')+'|'+target+'|'+file.name+'|'+file.size+'|'+(file.lastModified||0);return 'u'+fnv(s,2166136261)+fnv(s,2246822507)}
function targetDevice(id){for(var i=0;i<peers.length;i++)if(peers[i].id===id)return peers[i];return null}
function localURL(){var ips=(localInfo&&localInfo.ips)||[];return 'http://'+(ips.length?ips[0]:'127.0.0.1')+':'+(localInfo?localInfo.port:51888)}
function loadInfo(){ajax('GET','/api/info?ts='+Date.now(),null,function(x){var v=JSON.parse(x.responseText);localInfo=v;canManage=!!v.can_manage;secureMode=!!v.secure_mode;var ips=(v.ips||[]).join(', ')||'127.0.0.1';q('selfInfo').innerHTML=esc(v.name)+' · '+esc(ips)+':'+v.port+' · '+esc(v.os)+'/'+esc(v.arch)+' · v'+esc(v.version);q('modeBadge').className='badge '+(secureMode?'secure':'');q('modeBadge').innerHTML=secureMode?'安全模式 · paired transfer':'LAN only · direct transfer';if(canManage){q('manageArea').className='grid';q('historyCard').className='card';q('shareDirInput').value=v.share_dir||'';q('deviceNameInput').value=v.name||'';q('autostart').checked=!!v.autostart;q('secureMode').checked=secureMode;q('pairCode').innerHTML=esc(v.pair_code||'------');loadSecurity();loadHistory()}loadFiles()},function(){loadFiles()})}
function loadDevices(){ajax('GET','/api/devices?ts='+Date.now(),null,function(x){peers=JSON.parse(x.responseText);var html='',opts='<option value="local">当前设备（保存到共享目录）</option>',i,p;if(!peers.length)html='<div class="muted">暂未发现其他 LAN Share 设备</div>';for(i=0;i<peers.length;i++){p=peers[i];var lock=p.secure?'<span class="pill lock">安全</span>':'',trusted=p.trusted?'<span class="pill lock">已配对</span>':'';html+='<div class="device"><div><strong>'+esc(p.name)+'</strong>'+lock+trusted+'<div class="muted small">'+esc(p.ip)+':'+p.port+' · '+esc(p.os)+'/'+esc(p.arch)+'</div></div><div class="row">'+(p.secure&&!p.trusted?'<button class="pair" data-id="'+esc(p.id)+'">配对</button>':'')+(p.trusted?'<button class="unpair" data-id="'+esc(p.id)+'">取消配对</button>':'')+'<button class="browse" data-id="'+esc(p.id)+'">浏览文件</button><a class="btn" target="_blank" rel="noreferrer" href="http://'+esc(p.ip)+':'+p.port+'/">打开</a></div></div>';opts+='<option value="'+esc(p.id)+'">'+esc(p.name)+(p.secure?(p.trusted?' 🔒':' 🔐未配对'):'')+'</option>'}var cur=q('target').value;q('devices').innerHTML=html;q('target').innerHTML=opts;for(i=0;i<q('target').options.length;i++)if(q('target').options[i].value===cur)q('target').selectedIndex=i;bindDeviceButtons()},function(){q('devices').innerHTML='<div class="muted">设备发现读取失败</div>'})}
function bindDeviceButtons(){var bs=document.getElementsByClassName('pair'),i;for(i=0;i<bs.length;i++)bs[i].onclick=function(){pairDevice(this.getAttribute('data-id'))};bs=document.getElementsByClassName('unpair');for(i=0;i<bs.length;i++)bs[i].onclick=function(){unpairDevice(this.getAttribute('data-id'))};bs=document.getElementsByClassName('browse');for(i=0;i<bs.length;i++)bs[i].onclick=function(){browsePeer(this.getAttribute('data-id'))}}
function unpairDevice(id){var p=targetDevice(id);if(!p)return;if(!confirm('取消与 '+p.name+' 的配对？'))return;json('POST','/api/trust/revoke',{id:id,direction:'outgoing'},function(){loadDevices()},function(x){alert(x.responseText||'取消配对失败')})}
function pairDevice(id,cb){var p=targetDevice(id);if(!p)return;var code=prompt('请输入 '+p.name+' 本机页面显示的 6 位配对码：','');if(!code)return;json('POST','/api/pair-device',{device_id:id,code:code},function(){loadDevices();alert('已与 '+p.name+' 配对。后续 Agent 传输将自动认证并加密。');cb&&cb(true)},function(x){alert(x.responseText||'配对失败');cb&&cb(false)})}
function browsePeer(id){var p=targetDevice(id);if(!p)return;ajax('GET','/api/peer-files?device_id='+encodeURIComponent(id),null,function(x){var list=JSON.parse(x.responseText),html='<div class="section-title">'+esc(p.name)+' 的共享文件</div>';if(!list.length)html+='<div class="muted">暂无文件</div>';for(var i=0;i<list.length;i++){var f=list[i];html+='<div class="device"><div><strong>'+esc(f.name)+'</strong><div class="muted small">'+fmtBytes(f.size)+'</div></div><button class="pull" data-id="'+esc(id)+'" data-name="'+encodeURIComponent(f.name)+'">4 路高速拉取</button></div>'}q('remoteFiles').className='remote-files';q('remoteFiles').innerHTML=html;bindPullButtons()},function(x){if(x.status===401&&p.secure){pairDevice(id,function(ok){if(ok)browsePeer(id)})}else alert(x.responseText||'读取远程文件失败')})}
function bindPullButtons(){var bs=document.getElementsByClassName('pull'),i;for(i=0;i<bs.length;i++)bs[i].onclick=function(){pullFile(this,this.getAttribute('data-id'),decodeURIComponent(this.getAttribute('data-name')))}}
function pullFile(btn,id,name){btn.disabled=true;btn.innerHTML='拉取中...';var started=Date.now();json('POST','/api/pull',{device_id:id,name:name,parallel:4},function(x){btn.disabled=false;btn.innerHTML='4 路高速拉取';var v=JSON.parse(x.responseText);alert('完成：'+v.name+'\n平均速度：'+fmtBytes(v.bytes_per_second)+'/s'+(v.encrypted?'\nAES-256-GCM 加密':'')+'\n耗时：'+((Date.now()-started)/1000).toFixed(1)+' 秒');loadFiles();loadHistory()},function(x){btn.disabled=false;btn.innerHTML='4 路高速拉取';alert(x.responseText||'高速拉取失败')})}
function loadFiles(){ajax('GET','/api/files?ts='+Date.now(),null,function(x){q('browserPairBox').className='pairbox hidden';var list=JSON.parse(x.responseText),html='',i,f;if(!list.length){q('files').innerHTML='<tr><td colspan="4" class="muted">当前共享目录暂无文件</td></tr>';return}for(i=0;i<list.length;i++){f=list[i];var n=encodeURIComponent(f.name),del=canManage?' <button class="danger del" data-name="'+n+'">删除</button>':'';html+='<tr><td>'+esc(f.name)+'</td><td>'+fmtBytes(f.size)+'</td><td>'+new Date(f.mod_time*1000).toLocaleString()+'</td><td><a class="btn" href="/api/download?name='+n+'">下载</a>'+del+'</td></tr>'}q('files').innerHTML=html;bindDelete()},function(x){if(x.status===401&&!canManage){q('browserPairBox').className='pairbox';q('files').innerHTML='<tr><td colspan="4" class="muted">需要配对后查看文件</td></tr>'}else q('files').innerHTML='<tr><td colspan="4" class="muted">读取失败：'+esc(x.responseText||('HTTP '+x.status))+'</td></tr>'})}
function bindDelete(){var bs=document.getElementsByClassName('del'),i;for(i=0;i<bs.length;i++)bs[i].onclick=function(){var n=this.getAttribute('data-name');if(confirm('确认从共享目录删除？'))ajax('DELETE','/api/files?name='+n,null,loadFiles,function(x){alert(x.responseText||'删除失败')})}}
function browserPair(){var code=q('browserPairCode').value.replace(/\D/g,'');if(code.length!==6){alert('请输入 6 位配对码');return}json('POST','/api/browser-pair',{code:code,name:'Browser'},function(){q('browserPairBox').className='pairbox hidden';loadFiles()},function(x){alert(x.responseText||'配对失败')})}
function drawSpeed(){var c=q('speedChart'),ctx=c.getContext&&c.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,c.width,c.height);if(speedSamples.length<2)return;var max=1,i;for(i=0;i<speedSamples.length;i++)if(speedSamples[i]>max)max=speedSamples[i];ctx.beginPath();for(i=0;i<speedSamples.length;i++){var x=i*(c.width/(Math.max(1,speedSamples.length-1))),y=c.height-6-(speedSamples[i]/max)*(c.height-12);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.lineWidth=2;ctx.strokeStyle='#111827';ctx.stroke()}
function setProgress(file,done,total,startTime){var pct=total?done/total*100:100,elapsed=Math.max(.1,(Date.now()-startTime)/1000),speed=done/elapsed,eta=speed>0?(total-done)/speed:0;q('bar').style.width=Math.min(100,pct).toFixed(2)+'%';q('speedText').innerHTML=fmtBytes(speed)+'/s';q('etaText').innerHTML=eta>1?'预计 '+Math.ceil(eta)+' 秒':'';q('uploadStatus').innerHTML=esc(file.name)+' · '+pct.toFixed(1)+'% · '+fmtBytes(done)+' / '+fmtBytes(total);speedSamples.push(speed);if(speedSamples.length>60)speedSamples.shift();drawSpeed()}
function sendFiles(files){var list=[],i,target=q('target').value;for(i=0;i<files.length;i++)list.push(files[i]);var p=target==='local'?null:targetDevice(target);function go(ok){if(ok===false||!list.length){loadFiles();loadHistory();return}uploadChunked(list.shift(),target,go)}if(p&&p.secure&&!p.trusted){pairDevice(target,function(ok){if(ok)go(true)})}else go(true)}
function uploadChunked(file,target,done){var id=uploadID(file,target),startTime=Date.now(),retry=0;q('progressWrap').className='';speedSamples=[];drawSpeed();function init(){var u=target==='local'?'/api/uploads/init':'/api/relay/init?device_id='+encodeURIComponent(target);json('POST',u,{id:id,name:file.name,size:file.size},function(x){var v=JSON.parse(x.responseText);sendAt(v.offset||0,v.chunk_size||16777216)},function(x){var p=target==='local'?null:targetDevice(target);if(x.status===401&&p&&p.secure){pairDevice(target,function(ok){if(ok)init();else done(false)})}else{q('uploadStatus').innerHTML=esc(file.name+' · 初始化失败：'+(x.responseText||x.status));done(false)}})}function sendAt(offset,chunkSize){if(offset>=file.size){complete();return}var end=Math.min(file.size,offset+chunkSize),blob=file.slice(offset,end),u=target==='local'?'/api/uploads/chunk?id='+encodeURIComponent(id)+'&offset='+offset:'/api/relay/chunk?device_id='+encodeURIComponent(target)+'&id='+encodeURIComponent(id)+'&offset='+offset,x=new XMLHttpRequest();x.open('PUT',u,true);x.timeout=0;x.upload.onprogress=function(e){setProgress(file,offset+(e.loaded||0),file.size,startTime)};x.onload=function(){if(x.status>=200&&x.status<300){retry=0;var v=JSON.parse(x.responseText);setProgress(file,v.offset,file.size,startTime);sendAt(v.offset,chunkSize)}else if(x.status===409){try{var v2=JSON.parse(x.responseText);sendAt(v2.offset,chunkSize)}catch(e){retryChunk()}}else retryChunk()};x.onerror=retryChunk;x.send(blob);function retryChunk(){retry++;if(retry>3){q('uploadStatus').innerHTML=esc(file.name+' · 失败，已保留断点；再次发送同一文件可继续');done(false);return}q('uploadStatus').innerHTML=esc(file.name+' · 网络中断，正在恢复断点（'+retry+'/3）');setTimeout(init,700*retry)}}function complete(){var u=target==='local'?'/api/uploads/complete?id='+encodeURIComponent(id):'/api/relay/complete?device_id='+encodeURIComponent(target)+'&id='+encodeURIComponent(id);ajax('POST',u,null,function(x){setProgress(file,file.size,file.size,startTime);var v=JSON.parse(x.responseText);q('uploadStatus').innerHTML=esc(file.name+' · 完成 · '+fmtBytes(v.bytes_per_second||file.size/Math.max(.1,(Date.now()-startTime)/1000))+'/s'+(target!=='local'&&targetDevice(target)&&targetDevice(target).trusted?' · AES-256-GCM':'')+(v.resumed?' · 已续传':''));done(true)},function(x){q('uploadStatus').innerHTML=esc(file.name+' · 完成确认失败：'+(x.responseText||x.status));done(false)})}init()}
function changeDir(){var path=q('shareDirInput').value.replace(/^\s+|\s+$/g,'');if(!path)return;json('PUT','/api/share-dir',{path:path},function(x){var v=JSON.parse(x.responseText);q('shareDirInput').value=v.path;q('shareDirHint').innerHTML='已切换。新目录已有文件直接共享，无需上传。';loadFiles()},function(x){alert(x.responseText||'切换失败')})}
function saveName(){json('PUT','/api/settings',{name:q('deviceNameInput').value},function(){loadInfo();loadDevices()},function(x){alert(x.responseText||'保存失败')})}
function setAutostart(){json('PUT','/api/settings',{autostart:q('autostart').checked},function(){},function(x){q('autostart').checked=!q('autostart').checked;alert(x.responseText||'设置失败')})}
function setSecure(){json('PUT','/api/security',{secure_mode:q('secureMode').checked},function(){loadInfo();loadSecurity()},function(x){q('secureMode').checked=!q('secureMode').checked;alert(x.responseText||'设置失败')})}
function loadSecurity(){if(!canManage)return;ajax('GET','/api/security',null,function(x){var v=JSON.parse(x.responseText);q('secureMode').checked=!!v.secure_mode;q('pairCode').innerHTML=esc(v.pair_code||'------');var list=v.trusted||[],html='';if(!list.length)html='<div class="muted">暂无已授权设备</div>';for(var i=0;i<list.length;i++)html+='<div class="device"><div><strong>'+esc(list[i].name||list[i].id)+'</strong><div class="muted small">'+new Date(list[i].paired_at*1000).toLocaleString()+'</div></div><button class="danger revoke" data-id="'+esc(list[i].id)+'">撤销</button></div>';q('trustedList').innerHTML=html;var bs=document.getElementsByClassName('revoke');for(i=0;i<bs.length;i++)bs[i].onclick=function(){var id=this.getAttribute('data-id');json('POST','/api/trust/revoke',{id:id,direction:'incoming'},loadSecurity,function(x){alert(x.responseText||'撤销失败')})}},function(){})}
function regenPair(){json('PUT','/api/security',{regenerate_pair_code:true},function(x){q('pairCode').innerHTML=esc(JSON.parse(x.responseText).pair_code)},function(x){alert(x.responseText||'生成失败')})}
function copyAddr(){var text=localURL(),ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();try{document.execCommand('copy');q('updateStatus').innerHTML='已复制 '+esc(text)}catch(e){prompt('复制此地址：',text)}document.body.removeChild(ta)}
function checkUpdate(){q('updateStatus').innerHTML='检查中...';ajax('GET','/api/update-check',null,function(x){var v=JSON.parse(x.responseText);q('updateStatus').innerHTML=v.update_available?'发现 v'+esc(v.latest)+'，请到 GitHub Releases 更新':'当前已是最新版本'},function(x){q('updateStatus').innerHTML='检查失败（需要互联网）：'+esc(x.responseText||x.status)})}
function loadHistory(){if(!canManage)return;ajax('GET','/api/history',null,function(x){var list=JSON.parse(x.responseText),html='';if(!list.length)html='<tr><td colspan="7" class="muted">暂无传输记录</td></tr>';for(var i=0;i<list.length;i++){var r=list[i];html+='<tr><td>'+esc(r.direction)+'</td><td>'+esc(r.peer||'-')+'</td><td>'+esc(r.name)+'</td><td>'+fmtBytes(r.size)+'</td><td>'+fmtBytes(r.bytes_per_second)+'/s</td><td>'+(r.encrypted?'AES-GCM':'-')+(r.resumed?' / 续传':'')+'</td><td>'+new Date(r.finished_at*1000).toLocaleString()+'</td></tr>'}q('history').innerHTML=html},function(){})}
var drop=q('drop'),picker=q('file');drop.onclick=function(){picker.click()};picker.onchange=function(){sendFiles(picker.files)};['dragenter','dragover'].forEach(function(ev){drop.addEventListener(ev,function(e){e.preventDefault();drop.className='drop drag'})});drop.addEventListener('dragleave',function(e){e.preventDefault();drop.className='drop'});drop.addEventListener('drop',function(e){e.preventDefault();drop.className='drop';sendFiles(e.dataTransfer.files)});
q('refreshBtn').onclick=loadFiles;q('browserPairBtn').onclick=browserPair;q('changeDirBtn').onclick=changeDir;q('openDirBtn').onclick=function(){ajax('POST','/api/open-dir',null,function(){},function(x){alert(x.responseText||'打开失败')})};q('saveNameBtn').onclick=saveName;q('autostart').onchange=setAutostart;q('secureMode').onchange=setSecure;q('regenPairBtn').onclick=regenPair;q('copyAddrBtn').onclick=copyAddr;q('updateBtn').onclick=checkUpdate;q('historyBtn').onclick=loadHistory;
loadInfo();loadDevices();setInterval(loadDevices,3000);setInterval(loadFiles,6000);setInterval(loadHistory,10000);
})();
