(function(){
var state={info:null,peers:[],selectedPeer:null,devicePage:1,devicePageSize:6,filePage:1,filePageSize:10,fileQuery:'',remotePage:1,remotePageSize:10,remoteQuery:'',historyPage:1,historyPageSize:10,historyQuery:'',historyDirection:'',historyStatus:'',currentShare:null};
function q(id){return document.getElementById(id)}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function fmtBytes(n){var u=['B','KB','MB','GB','TB'],i=0;if(typeof n!=='number'||isNaN(n))return '-';while(n>=1024&&i<u.length-1){n/=1024;i++}return n.toFixed(i?1:0)+' '+u[i]}
function fmtSpeed(n){return n>0?fmtBytes(n)+'/s':'-'}
function fmtTime(ts){return ts?new Date(ts*1000).toLocaleString():'-'}
function ajax(method,url,body,ok,bad,type){var x=new XMLHttpRequest();x.open(method,url,true);x.timeout=0;if(type)x.setRequestHeader('Content-Type',type);x.onreadystatechange=function(){if(x.readyState===4){if(x.status>=200&&x.status<300){if(ok)ok(x)}else if(bad)bad(x)}};x.onerror=function(){if(bad)bad(x)};x.send(body==null?null:body);return x}
function json(method,url,obj,ok,bad){return ajax(method,url,obj==null?null:JSON.stringify(obj),ok,bad,'application/json; charset=utf-8')}
function copyText(text){var t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();try{document.execCommand('copy');toast('已复制到剪贴板')}catch(e){window.prompt('复制下面内容：',text)}document.body.removeChild(t)}
function toast(text,error){var el=q('toast');el.className='toast'+(error?' error':'');el.innerHTML=esc(text);setTimeout(function(){el.className='toast hidden'},2600)}
function debounce(fn,delay){var timer;return function(){var args=arguments;clearTimeout(timer);timer=setTimeout(function(){fn.apply(null,args)},delay)}}
function query(params){var out=[],k;for(k in params){if(params.hasOwnProperty(k)&&params[k]!==''&&params[k]!=null)out.push(encodeURIComponent(k)+'='+encodeURIComponent(params[k]))}return out.join('&')}
function localURL(){var inf=state.info||{},ips=inf.ips||[];return 'http://'+(ips[0]||'127.0.0.1')+':'+(inf.port||51888)}
function uploadID(file,target){var s=((state.info&&state.info.id)||'local')+'|'+target+'|'+file.name+'|'+file.size+'|'+(file.lastModified||0),h1=2166136261,h2=2246822507,i;for(i=0;i<s.length;i++){h1^=s.charCodeAt(i);h1=(h1*16777619)>>>0;h2^=s.charCodeAt(i);h2=(h2*16777619)>>>0}return 'u'+('00000000'+h1.toString(16)).slice(-8)+('00000000'+h2.toString(16)).slice(-8)}
function peerByID(id){for(var i=0;i<state.peers.length;i++)if(state.peers[i].id===id)return state.peers[i];return null}
function firstLetter(s){s=String(s||'L').trim();return s?s.charAt(0).toUpperCase():'L'}

function showPage(name){var pages=document.getElementsByClassName('page'),i;for(i=0;i<pages.length;i++)pages[i].className='page';q('page-'+name).className='page active';var bs=q('nav').getElementsByTagName('button');for(i=0;i<bs.length;i++)bs[i].className=bs[i].getAttribute('data-page')===name?'active':'';location.hash='#/'+name;if(name==='space')loadFiles();if(name==='devices'){loadDevices();if(state.selectedPeer)loadRemoteFiles()}if(name==='transfers')loadHistory();if(name==='settings'){loadInfo();loadSecurity()}}
function route(){var n=(location.hash||'#/space').replace(/^#\/?/,'');if(!q('page-'+n))n='space';showPage(n)}

function loadInfo(){ajax('GET','/api/info?ts='+Date.now(),null,function(x){var v=JSON.parse(x.responseText);state.info=v;var ip=(v.ips&&v.ips[0])||'127.0.0.1';q('topIP').innerHTML=esc(ip);q('sideIP').innerHTML=esc(ip);q('sideNetwork').innerHTML='局域网已连接';q('sideVersion').innerHTML='LAN Share v'+esc(v.version);q('avatar').innerHTML=esc(firstLetter(v.name));q('deviceName').value=v.name||'';q('shareDir').value=v.share_dir||'';q('autostart').checked=!!v.autostart;q('secureMode').checked=!!v.secure_mode;q('shareScope').value=v.secure_mode?'secure':'open';q('spaceSecurity').innerHTML=v.secure_mode?'● 仅配对设备':'● 局域网可访问';q('pairCode').innerHTML=esc(v.pair_code||'------')},function(){q('sideNetwork').innerHTML='连接异常'})}

function renderPager(id,page,pages,total,onGo){var el=q(id),html='',start,end,i;if(!el)return;if(!pages||pages<=1){el.innerHTML=total?'共 '+total+' 条':'';return}start=Math.max(1,page-2);end=Math.min(pages,start+4);if(end-start<4)start=Math.max(1,end-4);html+='<span>共 '+total+' 条</span><button data-p="'+Math.max(1,page-1)+'" '+(page<=1?'disabled':'')+'>‹</button>';for(i=start;i<=end;i++)html+='<button data-p="'+i+'" class="'+(i===page?'active':'')+'">'+i+'</button>';html+='<button data-p="'+Math.min(pages,page+1)+'" '+(page>=pages?'disabled':'')+'>›</button>';el.innerHTML=html;var bs=el.getElementsByTagName('button');for(i=0;i<bs.length;i++)bs[i].onclick=function(){if(this.disabled)return;onGo(parseInt(this.getAttribute('data-p'),10)||1)}}

function loadFiles(){var u='/api/files?'+query({paged:1,page:state.filePage,page_size:state.filePageSize,q:state.fileQuery,ts:Date.now()});ajax('GET',u,null,function(x){var v=JSON.parse(x.responseText),items=v.items||[],html='',i,f;q('fileCount').innerHTML=v.total||0;if(!items.length)html='<tr><td colspan="4" class="muted">暂无共享文件</td></tr>';for(i=0;i<items.length;i++){f=items[i];html+='<tr><td><div class="file-name"><span class="file-icon">▧</span><span>'+esc(f.name)+'</span></div></td><td>'+fmtBytes(f.size)+'</td><td>'+fmtTime(f.mod_time)+'</td><td><div class="table-actions"><button class="icon-action link-file" title="复制下载链接" data-name="'+encodeURIComponent(f.name)+'">⌁</button><button class="icon-action qr-file" title="生成二维码" data-name="'+encodeURIComponent(f.name)+'">▦</button><a class="icon-action btn" title="下载" href="/api/download?name='+encodeURIComponent(f.name)+'">⇩</a><button class="icon-action danger del-file" title="删除" data-name="'+encodeURIComponent(f.name)+'">×</button></div></td></tr>'}q('fileRows').innerHTML=html;state.filePage=v.page||1;renderPager('filePager',v.page||1,v.pages||0,v.total||0,function(p){state.filePage=p;loadFiles()});bindFileActions()},function(x){q('fileRows').innerHTML='<tr><td colspan="4" class="muted">读取失败：'+esc(x.responseText||x.status)+'</td></tr>'})}
function bindFileActions(){var i,bs=document.getElementsByClassName('del-file');for(i=0;i<bs.length;i++)bs[i].onclick=function(){var name=decodeURIComponent(this.getAttribute('data-name'));if(window.confirm('确认删除共享文件「'+name+'」？'))ajax('DELETE','/api/files?name='+encodeURIComponent(name),null,function(){toast('已删除 '+name);loadFiles()},function(x){toast(x.responseText||'删除失败',true)})};bs=document.getElementsByClassName('link-file');for(i=0;i<bs.length;i++)bs[i].onclick=function(){shareFile(decodeURIComponent(this.getAttribute('data-name')),false)};bs=document.getElementsByClassName('qr-file');for(i=0;i<bs.length;i++)bs[i].onclick=function(){shareFile(decodeURIComponent(this.getAttribute('data-name')),true)}}
function shareFile(name,showQR){findOrCreateShare(name,function(link){if(showQR)openShareModal(link);else copyText(link.url)})}
function findOrCreateShare(name,done){ajax('GET','/api/share-links?ts='+Date.now(),null,function(x){var list=JSON.parse(x.responseText),now=Math.floor(Date.now()/1000),i;for(i=0;i<list.length;i++)if(list[i].name===name&&list[i].expires_at>now+60){done(list[i]);return}createShare(name,done)},function(){createShare(name,done)})}
function createShare(name,done){json('POST','/api/share-links',{name:name,ttl_seconds:3600},function(x){done(JSON.parse(x.responseText))},function(x){toast(x.responseText||'创建分享链接失败',true)})}
function openShareModal(link){state.currentShare=link;q('shareModalTitle').innerHTML=esc(link.name);q('shareURL').innerHTML=esc(link.url);q('shareExpire').innerHTML='链接有效至 '+fmtTime(link.expires_at);var src='/api/share-links/qr?token='+encodeURIComponent(link.token)+'&ts='+Date.now();q('shareQR').src=src;q('downloadQR').href=src;q('shareModal').className='modal'}

function loadDevices(){ajax('GET','/api/devices?ts='+Date.now(),null,function(x){state.peers=JSON.parse(x.responseText)||[];q('peerCount').innerHTML='● '+state.peers.length+' 台在线';if(state.selectedPeer&&!peerByID(state.selectedPeer)){state.selectedPeer=null;q('remoteTitle').innerHTML='请选择设备';q('remoteFiles').className='remote-files hidden';q('remoteEmpty').className='remote-empty';q('uploadToPeer').disabled=true;q('remoteSearch').disabled=true}renderPeers()},function(){q('peerList').innerHTML='<div class="muted">设备发现读取失败</div>'})}
function renderPeers(){var total=state.peers.length,pages=total?Math.ceil(total/state.devicePageSize):0;if(pages&&state.devicePage>pages)state.devicePage=pages;var start=(state.devicePage-1)*state.devicePageSize,end=Math.min(total,start+state.devicePageSize),html='',i,p;if(!total)html='<div class="remote-empty"><div>⌁</div><strong>未发现其他设备</strong><span>请确认对方已启动 LAN Share 并连接同一局域网</span></div>';for(i=start;i<end;i++){p=state.peers[i];html+='<div class="peer '+(p.id===state.selectedPeer?'active':'')+'" data-id="'+esc(p.id)+'"><div class="peer-icon">'+(p.os==='darwin'?'▰':'▣')+'</div><div class="peer-info"><strong>'+esc(p.name)+'</strong><span>'+esc(p.ip)+':'+p.port+' · '+esc(p.os||'unknown')+(p.trusted?' · 已配对':'')+'</span></div><div class="peer-status"><i></i>'+(p.secure&&!p.trusted?'需配对':'在线')+'</div></div>'}q('peerList').innerHTML=html;renderPager('peerPager',state.devicePage,pages,total,function(pg){state.devicePage=pg;renderPeers()});var cards=q('peerList').getElementsByClassName('peer');for(i=0;i<cards.length;i++)cards[i].onclick=function(){selectPeer(this.getAttribute('data-id'))}}
function selectPeer(id){var p=peerByID(id);if(!p)return;state.selectedPeer=id;state.remotePage=1;state.remoteQuery='';q('remoteSearch').value='';q('remoteTitle').innerHTML=esc(p.name)+' 的文件';q('remoteSubtitle').innerHTML='选择文件下载到当前设备，或向该设备上传文件';q('remoteEmpty').className='remote-empty hidden';q('remoteFiles').className='remote-files';q('uploadToPeer').disabled=false;q('remoteSearch').disabled=false;renderPeers();loadRemoteFiles()}
function loadRemoteFiles(){var p=peerByID(state.selectedPeer);if(!p)return;var u='/api/peer-files?'+query({device_id:p.id,page:state.remotePage,page_size:state.remotePageSize,q:state.remoteQuery,ts:Date.now()});ajax('GET',u,null,function(x){var v=JSON.parse(x.responseText),items=v.items||[],html='',i,f;if(!items.length)html='<div class="remote-empty"><div>▧</div><strong>该设备暂无共享文件</strong><span>可以直接上传文件到这台设备</span></div>';for(i=0;i<items.length;i++){f=items[i];html+='<div class="remote-file"><span class="file-icon">▧</span><div class="meta"><strong>'+esc(f.name)+'</strong><span>'+fmtBytes(f.size)+' · '+fmtTime(f.mod_time)+'</span></div><button class="pull-file" data-name="'+encodeURIComponent(f.name)+'">下载</button></div>'}q('remoteRows').innerHTML=html;state.remotePage=v.page||1;renderPager('remotePager',v.page||1,v.pages||0,v.total||0,function(pg){state.remotePage=pg;loadRemoteFiles()});var bs=document.getElementsByClassName('pull-file');for(i=0;i<bs.length;i++)bs[i].onclick=function(){pullRemote(decodeURIComponent(this.getAttribute('data-name')),this)}},function(x){if(x.status===401&&p.secure){pairPeer(p,function(ok){if(ok)loadRemoteFiles()})}else{q('remoteRows').innerHTML='<div class="remote-empty"><strong>读取失败</strong><span>'+esc(x.responseText||('HTTP '+x.status))+'</span></div>'}})}
function pairPeer(p,cb){var code=window.prompt('请输入 '+p.name+' 上显示的 6 位配对码：','');if(!code){if(cb)cb(false);return}json('POST','/api/pair-device',{device_id:p.id,code:String(code).replace(/\D/g,'')},function(){toast('已与 '+p.name+' 配对');loadDevices();if(cb)cb(true)},function(x){toast(x.responseText||'配对失败',true);if(cb)cb(false)})}
function pullRemote(name,btn){var p=peerByID(state.selectedPeer);if(!p)return;btn.disabled=true;btn.innerHTML='下载中…';json('POST','/api/pull',{device_id:p.id,name:name,parallel:4},function(x){btn.disabled=false;btn.innerHTML='下载';var v=JSON.parse(x.responseText);toast('已下载 '+v.name+' · '+fmtSpeed(v.bytes_per_second));loadFiles();loadHistory()},function(x){btn.disabled=false;btn.innerHTML='下载';if(x.status===401&&p.secure)pairPeer(p,function(ok){if(ok)pullRemote(name,btn)});else toast(x.responseText||'下载失败',true)})}

function setProgress(prefix,file,done,total,start){var pct=total?done*100/total:100,speed=done/Math.max(.1,(Date.now()-start)/1000);q(prefix+'Progress').className='upload-progress';q(prefix+'ProgressName').innerHTML=esc(file.name);q(prefix+'ProgressText').innerHTML=pct.toFixed(1)+'%';q(prefix+'ProgressBar').style.width=Math.min(100,pct).toFixed(1)+'%';q(prefix+'ProgressSpeed').innerHTML=fmtSpeed(speed)+' · '+fmtBytes(done)+' / '+fmtBytes(total)}
function sendFiles(fileList,target,prefix){var files=[],i;for(i=0;i<fileList.length;i++)files.push(fileList[i]);function next(ok){if(ok===false||!files.length){loadFiles();loadHistory();if(target!=='local')loadRemoteFiles();return}uploadOne(files.shift(),target,prefix,next)}var p=target==='local'?null:peerByID(target);if(p&&p.secure&&!p.trusted)pairPeer(p,function(ok){if(ok)next(true)});else next(true)}
function uploadOne(file,target,prefix,done){var id=uploadID(file,target),start=Date.now(),retry=0;function init(){var u=target==='local'?'/api/uploads/init':'/api/relay/init?device_id='+encodeURIComponent(target);json('POST',u,{id:id,name:file.name,size:file.size},function(x){var v=JSON.parse(x.responseText);chunk(v.offset||0,v.chunk_size||16777216)},function(x){var p=peerByID(target);if(x.status===401&&p)pairPeer(p,function(ok){if(ok)init();else done(false)});else{toast(x.responseText||'上传初始化失败',true);done(false)}})}function chunk(offset,size){if(offset>=file.size){complete();return}var end=Math.min(file.size,offset+size),u=target==='local'?'/api/uploads/chunk?id='+encodeURIComponent(id)+'&offset='+offset:'/api/relay/chunk?device_id='+encodeURIComponent(target)+'&id='+encodeURIComponent(id)+'&offset='+offset,x=new XMLHttpRequest();x.open('PUT',u,true);x.timeout=0;x.upload.onprogress=function(e){setProgress(prefix,file,offset+(e.loaded||0),file.size,start)};x.onload=function(){if(x.status>=200&&x.status<300){retry=0;var v=JSON.parse(x.responseText);setProgress(prefix,file,v.offset,file.size,start);chunk(v.offset,size)}else recover()};x.onerror=recover;x.send(file.slice(offset,end));function recover(){retry++;if(retry>3){toast(file.name+' 上传中断，断点已保留',true);done(false);return}setTimeout(init,600*retry)}}function complete(){var u=target==='local'?'/api/uploads/complete?id='+encodeURIComponent(id):'/api/relay/complete?device_id='+encodeURIComponent(target)+'&id='+encodeURIComponent(id);ajax('POST',u,null,function(){setProgress(prefix,file,file.size,file.size,start);toast(file.name+' 上传完成');done(true)},function(x){toast(x.responseText||'上传完成确认失败',true);done(false)})}init()}

function loadHistory(){var u='/api/history?'+query({paged:1,page:state.historyPage,page_size:state.historyPageSize,q:state.historyQuery,direction:state.historyDirection,status:state.historyStatus,ts:Date.now()});ajax('GET',u,null,function(x){var v=JSON.parse(x.responseText),items=v.items||[],html='',i,r,label,status;if(!items.length)html='<tr><td colspan="7" class="muted">暂无传输记录</td></tr>';for(i=0;i<items.length;i++){r=items[i];label=r.direction==='send'?'↑ 发送':'↓ 接收';status=r.status==='completed'?'已完成':r.status;html+='<tr><td class="'+(r.direction==='send'?'send':'receive')+'">'+label+'</td><td><strong>'+esc(r.name)+'</strong></td><td>'+esc(r.peer||'本机')+'</td><td>'+fmtBytes(r.size)+'</td><td>'+esc(status)+(r.resumed?' · 续传':'')+'</td><td>'+fmtSpeed(r.bytes_per_second)+'</td><td>'+fmtTime(r.finished_at)+'</td></tr>'}q('historyRows').innerHTML=html;q('historyTotal').innerHTML='共 '+(v.total||0)+' 条';state.historyPage=v.page||1;renderPager('historyPager',v.page||1,v.pages||0,v.total||0,function(pg){state.historyPage=pg;loadHistory()})},function(x){q('historyRows').innerHTML='<tr><td colspan="7" class="muted">读取失败：'+esc(x.responseText||x.status)+'</td></tr>'})}

function loadSecurity(){ajax('GET','/api/security?ts='+Date.now(),null,function(x){var v=JSON.parse(x.responseText),list=v.trusted||[],html='',i,t;q('secureMode').checked=!!v.secure_mode;q('pairCode').innerHTML=esc(v.pair_code||'------');q('trustedCount').innerHTML=list.length+' 台';if(!list.length)html='<div class="muted" style="font-size:10px;padding:12px 0">暂无已授权设备</div>';for(i=0;i<list.length;i++){t=list[i];html+='<div class="trusted"><div><strong>'+esc(t.name||t.id)+'</strong><span>'+fmtTime(t.paired_at)+'</span></div><button class="revoke-trust" data-id="'+esc(t.id)+'">移除</button></div>'}q('trustedList').innerHTML=html;var bs=document.getElementsByClassName('revoke-trust');for(i=0;i<bs.length;i++)bs[i].onclick=function(){var id=this.getAttribute('data-id');json('POST','/api/trust/revoke',{id:id,direction:'incoming'},function(){loadSecurity();toast('已移除授权')},function(y){toast(y.responseText||'移除失败',true)})}},function(){})}
function saveSettings(){var name=q('deviceName').value.replace(/^\s+|\s+$/g,''),dir=q('shareDir').value.replace(/^\s+|\s+$/g,''),pending=0,failed=false;function done(){pending--;if(pending<=0&&!failed){toast('设置已保存');loadInfo();loadDevices();loadFiles()}}pending++;json('PUT','/api/settings',{name:name,autostart:q('autostart').checked},done,function(x){failed=true;toast(x.responseText||'保存设置失败',true)});if(dir&&(!state.info||dir!==state.info.share_dir)){pending++;json('PUT','/api/share-dir',{path:dir},done,function(x){failed=true;toast(x.responseText||'切换共享目录失败',true)})}}
function setSecure(v,after){json('PUT','/api/security',{secure_mode:v},function(){q('shareScope').value=v?'secure':'open';q('secureMode').checked=v;q('spaceSecurity').innerHTML=v?'● 仅配对设备':'● 局域网可访问';toast(v?'安全模式已开启':'已允许局域网访问');if(after)after()},function(x){toast(x.responseText||'安全设置失败',true);loadInfo()})}

function bind(){var nav=q('nav').getElementsByTagName('button'),i;for(i=0;i<nav.length;i++)nav[i].onclick=function(){showPage(this.getAttribute('data-page'))};window.onhashchange=route;
q('chooseLocalFiles').onclick=function(e){e.stopPropagation();q('localFilePicker').click()};q('localDrop').onclick=function(){q('localFilePicker').click()};q('localFilePicker').onchange=function(){sendFiles(this.files,'local','space');this.value=''};['dragenter','dragover'].forEach(function(ev){q('localDrop').addEventListener(ev,function(e){e.preventDefault();q('localDrop').className='dropzone drag'})});q('localDrop').ondragleave=function(){q('localDrop').className='dropzone'};q('localDrop').ondrop=function(e){e.preventDefault();q('localDrop').className='dropzone';sendFiles(e.dataTransfer.files,'local','space')};
q('shareScope').onchange=function(){setSecure(this.value==='secure')};q('changeShareDirQuick').onclick=function(){var cur=(state.info&&state.info.share_dir)||'',path=window.prompt('输入要共享的文件夹路径：',cur);if(path)json('PUT','/api/share-dir',{path:path},function(){toast('共享目录已切换');loadInfo();loadFiles()},function(x){toast(x.responseText||'切换失败',true)})};q('refreshFiles').onclick=loadFiles;q('fileSearch').oninput=debounce(function(){state.fileQuery=q('fileSearch').value;state.filePage=1;loadFiles()},250);q('filePageSize').onchange=function(){state.filePageSize=parseInt(this.value,10)||10;state.filePage=1;loadFiles()};
q('remoteSearch').oninput=debounce(function(){state.remoteQuery=q('remoteSearch').value;state.remotePage=1;loadRemoteFiles()},250);q('remotePageSize').onchange=function(){state.remotePageSize=parseInt(this.value,10)||10;state.remotePage=1;loadRemoteFiles()};q('uploadToPeer').onclick=function(){if(state.selectedPeer)q('remoteUploadPicker').click()};q('remoteUploadPicker').onchange=function(){if(state.selectedPeer)sendFiles(this.files,state.selectedPeer,'peer');this.value=''};q('openManualIP').onclick=function(){var ip=q('manualIP').value.replace(/^\s+|\s+$/g,'');if(ip)window.open('http://'+ip+':'+((state.info&&state.info.port)||51888)+'/','_blank')};
q('historySearch').oninput=debounce(function(){state.historyQuery=q('historySearch').value;state.historyPage=1;loadHistory()},250);q('historyDirection').onchange=function(){state.historyDirection=this.value;state.historyPage=1;loadHistory()};q('historyStatus').onchange=function(){state.historyStatus=this.value;state.historyPage=1;loadHistory()};q('historyPageSize').onchange=function(){state.historyPageSize=parseInt(this.value,10)||10;state.historyPage=1;loadHistory()};
q('saveSettings').onclick=saveSettings;q('openShareDir').onclick=function(){ajax('POST','/api/open-dir',null,function(){},function(x){toast(x.responseText||'打开目录失败',true)})};q('secureMode').onchange=function(){setSecure(this.checked)};q('copyPairCode').onclick=function(){copyText(q('pairCode').textContent||q('pairCode').innerText)};q('regenPairCode').onclick=function(){json('PUT','/api/security',{regenerate_pair_code:true},function(x){var v=JSON.parse(x.responseText);q('pairCode').innerHTML=esc(v.pair_code);toast('已生成新配对码')},function(x){toast(x.responseText||'生成失败',true)})};q('checkUpdate').onclick=function(){q('updateText').innerHTML='检查中…';ajax('GET','/api/update-check',null,function(x){var v=JSON.parse(x.responseText);q('updateText').innerHTML=v.update_available?'发现 v'+esc(v.latest):'当前已是最新版本'},function(){q('updateText').innerHTML='检查失败'})};
q('closeShareModal').onclick=function(){q('shareModal').className='modal hidden'};q('shareModal').onclick=function(e){if(e.target===q('shareModal'))q('shareModal').className='modal hidden'};q('copyShareURL').onclick=function(){if(state.currentShare)copyText(state.currentShare.url)};
}
bind();loadInfo();loadDevices();route();setInterval(loadDevices,3500);setInterval(function(){var page=(location.hash||'#/space').replace(/^#\/?/,'');if(page==='space')loadFiles();if(page==='transfers')loadHistory()},10000);
})();
