(function(){
var info=null,peers=[];
function q(id){return document.getElementById(id)}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function fmt(n){var u=['B','KB','MB','GB','TB'],i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return n.toFixed(i?1:0)+' '+u[i]}
function ajax(method,url,body,ok,bad,type){var x=new XMLHttpRequest();x.open(method,url,true);x.timeout=0;if(type)x.setRequestHeader('Content-Type',type);x.onreadystatechange=function(){if(x.readyState===4)(x.status>=200&&x.status<300?ok:bad||function(){})(x)};x.onerror=function(){(bad||function(){})(x)};x.send(body==null?null:body)}
function json(method,url,obj,ok,bad){ajax(method,url,obj==null?null:JSON.stringify(obj),ok,bad,'application/json; charset=utf-8')}
function copy(text){var t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();try{document.execCommand('copy')}catch(e){prompt('复制：',text)}document.body.removeChild(t)}
function uid(file,target){var s=((info&&info.id)||'local')+'|'+target+'|'+file.name+'|'+file.size+'|'+(file.lastModified||0),h=2166136261;for(var i=0;i<s.length;i++){h^=s.charCodeAt(i);h=(h*16777619)>>>0}return 'v07'+('00000000'+h.toString(16)).slice(-8)+file.size.toString(16)}
function peer(id){for(var i=0;i<peers.length;i++)if(peers[i].id===id)return peers[i];return null}
function reloadPeers(){ajax('GET','/api/devices?ts='+Date.now(),null,function(x){try{peers=JSON.parse(x.responseText)}catch(e){}})}

function bindAirDrop(){var box=q('devices');if(!box)return;var cards=box.getElementsByClassName('device');for(var i=0;i<cards.length;i++){var card=cards[i];if(card.getAttribute('data-v07-drop'))continue;var tagged=card.querySelector('[data-id]');if(!tagged)continue;var id=tagged.getAttribute('data-id');card.setAttribute('data-v07-drop','1');card.className+=' drop-target';var hint=document.createElement('div');hint.className='drop-hint';hint.innerHTML='拖文件到此设备直接发送';var left=card.firstElementChild;if(left)left.appendChild(hint);card.ondragover=function(e){e.preventDefault();this.className='device drop-target drag'};card.ondragleave=function(){this.className='device drop-target'};(function(c,target){c.ondrop=function(e){e.preventDefault();c.className='device drop-target';sendTo(e.dataTransfer.files,target)}})(card,id)}}
function sendTo(fileList,target){var files=[],i;for(i=0;i<fileList.length;i++)files.push(fileList[i]);function next(){if(!files.length){if(q('refreshBtn'))q('refreshBtn').click();return}sendOne(files.shift(),target,next)}next()}
function sendOne(file,target,done){var id=uid(file,target),started=Date.now(),retry=0;q('progressWrap').className='';function progress(n){var sec=Math.max(.1,(Date.now()-started)/1000),speed=n/sec,pct=file.size?n/file.size*100:100;q('bar').style.width=Math.min(100,pct).toFixed(2)+'%';q('speedText').innerHTML=fmt(speed)+'/s';q('etaText').innerHTML=speed>0&&n<file.size?'预计 '+Math.ceil((file.size-n)/speed)+' 秒':'';q('uploadStatus').innerHTML=esc(file.name)+' · AirDrop '+pct.toFixed(1)+'%'}function init(){json('POST','/api/relay/init?device_id='+encodeURIComponent(target),{id:id,name:file.name,size:file.size},function(x){var v=JSON.parse(x.responseText);chunk(v.offset||0,v.chunk_size||16777216)},function(x){if(x.status===401){var p=peer(target),code=prompt('请输入 '+(p?p.name:'目标设备')+' 的 6 位配对码：','');if(code)json('POST','/api/pair-device',{device_id:target,code:code},init,function(y){alert(y.responseText||'配对失败');done()});else done()}else{alert(x.responseText||'发送初始化失败');done()}})}function chunk(offset,size){if(offset>=file.size){complete();return}var end=Math.min(file.size,offset+size),x=new XMLHttpRequest();x.open('PUT','/api/relay/chunk?device_id='+encodeURIComponent(target)+'&id='+encodeURIComponent(id)+'&offset='+offset,true);x.timeout=0;x.upload.onprogress=function(e){progress(offset+(e.loaded||0))};x.onload=function(){if(x.status>=200&&x.status<300){retry=0;var v=JSON.parse(x.responseText);progress(v.offset);chunk(v.offset,size)}else recover()};x.onerror=recover;x.send(file.slice(offset,end));function recover(){retry++;if(retry>3){q('uploadStatus').innerHTML=esc(file.name+' · 网络中断，断点已保留');done();return}setTimeout(init,600*retry)}}function complete(){ajax('POST','/api/relay/complete?device_id='+encodeURIComponent(target)+'&id='+encodeURIComponent(id),null,function(){progress(file.size);q('uploadStatus').innerHTML=esc(file.name+' · AirDrop 完成');done()},function(x){alert(x.responseText||'完成确认失败');done()})}init()}

function injectShareButtons(){if(!info||!info.can_manage)return;var body=q('files');if(!body)return;var rows=body.getElementsByTagName('tr');for(var i=0;i<rows.length;i++){var cells=rows[i].getElementsByTagName('td');if(cells.length<4||rows[i].getAttribute('data-v07-share'))continue;var name=cells[0].textContent||cells[0].innerText;if(!name)continue;rows[i].setAttribute('data-v07-share','1');var b=document.createElement('button');b.className='share-file-v07';b.innerHTML='快速分享';(function(n){b.onclick=function(){createShare(n)}})(name);cells[3].insertBefore(b,cells[3].lastChild)}}
function createShare(name){var mins=parseInt(prompt('链接有效多少分钟？（1-1440）','10'),10);if(!mins)return;mins=Math.max(1,Math.min(1440,mins));json('POST','/api/share-links',{name:name,ttl_seconds:mins*60},function(x){var v=JSON.parse(x.responseText);showShare(v);loadLinks()},function(x){alert(x.responseText||'生成临时分享失败')})}
function showShare(v){var p=q('sharePreview');p.className='share-preview';p.innerHTML='<strong>'+esc(v.name)+'</strong><div class="share-url">'+esc(v.url)+'</div><div class="row"><img alt="QR" src="/api/share-links/qr?token='+encodeURIComponent(v.token)+'"><div><div class="muted small">有效至 '+new Date(v.expires_at*1000).toLocaleString()+'</div><div style="margin-top:10px"><button id="v07copy">复制链接</button></div></div></div>';q('v07copy').onclick=function(){copy(v.url)}}
function loadLinks(){if(!info||!info.can_manage)return;ajax('GET','/api/share-links?ts='+Date.now(),null,function(x){var list=JSON.parse(x.responseText),html='';if(!list.length)html='<div class="muted">暂无临时分享</div>';for(var i=0;i<list.length;i++){var v=list[i];html+='<div class="share-row"><div><strong>'+esc(v.name)+'</strong><div class="muted small">'+fmt(v.size)+' · 到期 '+new Date(v.expires_at*1000).toLocaleString()+'</div></div><div class="row"><button class="v07show" data-i="'+i+'">二维码</button><button class="v07copy" data-i="'+i+'">复制</button><button class="danger v07revoke" data-i="'+i+'">撤销</button></div></div>'}q('shareLinks').innerHTML=html;var b=q('shareLinks').getElementsByTagName('button');for(i=0;i<b.length;i++)b[i].onclick=function(){var v=list[parseInt(this.getAttribute('data-i'),10)];if(this.className.indexOf('v07show')>=0)showShare(v);else if(this.className.indexOf('v07copy')>=0)copy(v.url);else ajax('DELETE','/api/share-links?token='+encodeURIComponent(v.token),null,function(){q('sharePreview').className='share-preview hidden';loadLinks()})}},function(){})}
function init(){ajax('GET','/api/info?ts='+Date.now(),null,function(x){info=JSON.parse(x.responseText);if(info.can_manage){var h=q('trayHint');if(h)h.innerHTML=info.os==='windows'?'Windows 原生托盘已支持：双击托盘打开 LAN Share，右键可退出。':'当前平台继续使用零 CGO 浏览器 UI；Windows 构建额外提供原生托盘。';loadLinks();injectShareButtons()}},function(){});reloadPeers();var d=q('devices'),f=q('files');if(window.MutationObserver){if(d)new MutationObserver(bindAirDrop).observe(d,{childList:true,subtree:true});if(f)new MutationObserver(injectShareButtons).observe(f,{childList:true,subtree:true})}setInterval(function(){reloadPeers();bindAirDrop();injectShareButtons()},2500);if(q('shareLinksBtn'))q('shareLinksBtn').onclick=loadLinks}
init();
})();
